#this is the first make file of me 

#OBJ:
#     Type.i \
#	 Type.o \
#	 Type.s

Type.o: Type.c Type.h    	 
	  gcc -E Type.c > Type.i
	  gcc -Wall -S Type.c	  
	  gcc -c Type.c -o Type.o 
	  #gcc -o Type.c Type	  

#clean: 
 #     Type.i 
     	  
	